# Read the Docs configuration file for MkDocs projects
# See https://www.mkdocs.org/ for MkDocs documentation

# Required section for MkDocs builds on Read the Docs
build:
  os: ubuntu-22.04  # Specify the operating system (optional)
  tools:
    python: "3.12"  # Specify the Python version (optional)

# MkDocs configuration file path (relative to project root)
mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
# in a requirements.txt file within your docs directory
python:
  install:
    - requirements: docs/requirements.txt
