# Read the Docs configuration file for MkDocs projects
# See https://www.mkdocs.org/ for MkDocs documentation

# MkDocs configuration file path (relative to project root)
mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
# in a requirements.txt file within your docs directory
python:
  install:
    - requirements: requirements.txt
