# API Server Configuration
server:
  # Hostname or IP address to listen on (default: 127.0.0.1)
  host: 0.0.0.0
  # Port number to listen on (default: 5000)
  port: 5000
  # Enable debug mode for development (default: False)
  debug: true

# Database Configuration
database:
  # Database type
  type: mysql
  # Username for database access
  username: user
  # Password for database access
  password: pass
  # Database name
  db_name: your_database_name

# Optional logging configuration
logging:
  # Log level (e.g., debug, info, warning, error)
  level: info
  # Path to the log file (optional)
  # filename: app.log
